# Generated by Django 5.0.6 on 2024-07-13 16:59

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="AGC",
            fields=[
                ("id_agc", models.AutoField(primary_key=True, serialize=False)),
                (
                    "descripcion_agc",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("anio_agc", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Indicador",
            fields=[
                ("id_indicador", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_indicador", models.CharField(max_length=255)),
                (
                    "descripcion_indicador",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("fuente", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Objetivo",
            fields=[
                ("id_objetivo", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_objetivo", models.CharField(max_length=255)),
                (
                    "descripcion_objetivo",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("perspectiva", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="UGC",
            fields=[
                ("id_ugc", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_ugc", models.CharField(max_length=255)),
                (
                    "descripcion_ugc",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "responsable_ugc",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("fecha_crea_ugc", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="AcuerdoIndicadores",
            fields=[
                (
                    "id_acuerdo_indicador",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("valor_min", models.DecimalField(decimal_places=2, max_digits=10)),
                ("valor_opt", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "valor_obtenido",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "peso_indicador",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "resultado_indicador",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "porcentaje_conseguido",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "id_agc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.agc"
                    ),
                ),
                (
                    "id_indicador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.indicador",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="indicador",
            name="id_objetivo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapp.objetivo"
            ),
        ),
        migrations.AddField(
            model_name="agc",
            name="id_ugc",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapp.ugc"
            ),
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "descripcion_usuario",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("perfil", models.CharField(blank=True, max_length=255, null=True)),
                ("fecha_crea_usuario", models.DateField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "id_ugc",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.ugc",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("id_usuario", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_usuario", models.CharField(max_length=255)),
                (
                    "descripcion_usuario",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("login", models.CharField(max_length=255)),
                ("psw", models.CharField(max_length=255)),
                ("perfil", models.CharField(max_length=255)),
                ("fecha_crea_usuario", models.DateField(blank=True, null=True)),
                (
                    "id_ugc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.ugc"
                    ),
                ),
            ],
        ),
    ]
